
/*1. name, city
2. recency_days — days since last delivered order (CURRENT_DATE - MAX(order_date)). No orders = 9999.
3. frequency — count of delivered orders
4. monetary — total delivered revenue (₹0 if none)
5. r_score — NTILE(4) ORDER BY recency ASC (low = recent = best = score 1)
6. f_score — NTILE(4) ORDER BY frequency DESC (high = frequent = best = score 1)
7. m_score — NTILE(4) ORDER BY monetary DESC (high = big spender = best = score 1)
8. rfm_segment — CASE-based label: Champions, Loyal, Big Spenders, At Risk, Lost, Needs Attention*/

WITH ORDER_DATA AS (
SELECT 
	C.CUSTOMER_ID, C.NAME,
	CURRENT_DATE - MAX(O.ORDER_DATE) AS RECENCY_DAYS,
	COUNT(DISTINCT O.ORDER_ID) AS FREQUENCY,
	COALESCE(SUM(OI.QUANTITY*P.PRICE),0) AS MONETARY
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID AND O.STATUS='Delivered'
LEFT JOIN ORDER_ITEMS OI ON O.ORDER_ID=OI.ORDER_ID
LEFT JOIN PRODUCTS P ON P.PRODUCT_ID=OI.PRODUCT_ID
GROUP BY C.CUSTOMER_ID,1
),
RFM AS(
SELECT 
	*, 
	NTILE(4) OVER(ORDER BY RECENCY_DAYS) AS R_SCORE,
	NTILE(4) OVER(ORDER BY FREQUENCY DESC) AS F_SCORE,
	NTILE(4) OVER(ORDER BY MONETARY DESC) AS M_SCORE
FROM ORDER_DATA
)
SELECT * ,
	CASE 
		WHEN R_SCORE=1 AND F_SCORE=1 AND M_SCORE=1 THEN 'CHAMPION'
		WHEN R_SCORE=1 AND F_SCORE=1 THEN 'LOYAL CUSTOMERS'
		WHEN R_SCORE=1 AND M_SCORE=1 THEN 'BIG SPENDERS'
		WHEN R_SCORE=3 AND F_SCORE=1 THEN 'AT RISK'
		WHEN R_SCORE=4 AND F_SCORE=4 AND M_SCORE=4 THEN 'LOST'
		WHEN F_SCORE=1 AND M_SCORE=1 THEN 'LOYAL BIG SPENDERS'
		ELSE 'NEED ATTENTION'
		END AS rfm_segment
FROM RFM

/*"Now show me a SUMMARY — how many customers are in each RFM segment, and what's each segment's total revenue 
and average monetary value?"
Group by rfm_segment. Show: segment, customer_count, total_revenue, avg_revenue, pct_of_customers. 
Sort by total_revenue DESC.*/


WITH RFM AS (
SELECT
	C.CUSTOMER_ID,
	C.NAME,
	C.CITY,
	CURRENT_DATE - MAX(O.ORDER_DATE) AS recency_days,
	COALESCE(COUNT(DISTINCT O.ORDER_ID),0)	AS frequency,
	COALESCE(SUM(OI.QUANTITY*P.PRICE),0)	AS monetary
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID AND O.STATUS='Delivered'
LEFT JOIN ORDER_ITEMS OI ON OI.ORDER_ID=O.ORDER_ID
LEFT JOIN PRODUCTS P ON P.PRODUCT_ID=OI.PRODUCT_ID
GROUP BY 1,2,3
),
RFM_SCORE AS (
SELECT * , 
	NTILE(4) OVER(ORDER BY recency_days) AS R_SCORE,
	NTILE(4) OVER(ORDER BY frequency DESC) AS F_SCORE,
	NTILE(4) OVER(ORDER BY monetary DESC) AS M_SCORE
FROM RFM
),
RFM_SEGMENT AS (
SELECT *,
	CASE 	
		WHEN R_SCORE=1 AND F_SCORE=1 AND M_SCORE=1 THEN 'CHAMPION'
		WHEN R_SCORE=1 AND F_SCORE=1 THEN 'LOYAL CUSTOMERS'
		WHEN R_SCORE=1 AND M_SCORE=1 THEN 'BIG SPENDERS'
		WHEN R_SCORE=3 AND F_SCORE=1 THEN 'AT RISK'
		WHEN R_SCORE=4 AND F_SCORE=4 AND M_SCORE=4 THEN 'LOST'
		WHEN F_SCORE=1 AND M_SCORE=1 THEN 'LOYAL BIG SPENDERS'
		ELSE 'NEED ATTENTION'
		END AS rfm_segment
FROM RFM_SCORE
)
SELECT 
	rfm_segment, 
	COUNT(DISTINCT CUSTOMER_ID) AS CUST_COUNT,
	SUM(MONETARY) AS TOTAL_REV,
	ROUND(AVG(MONETARY),2) AS AVG_REV,
	ROUND(COUNT(*)::NUMERIC /SUM(COUNT(*)) OVER() * 100,2) AS pct_of_customers
FROM RFM_SEGMENT
GROUP BY 1

/*
"For each signup month cohort: how many customers joined, how many ordered in Month 0 (same month as signup), 
Month 1 (next month), Month 2, Month 3? Show both counts and retention percentages."
Cohort analysis: signup_month, cohort_size, month_0_orders, month_1_orders, month_2_orders, with retention % for each.*/


WITH COHORT AS (
SELECT CUSTOMER_ID, 
	DATE_TRUNC('MONTH',SIGNUP_DATE) AS COHORT_MONTH
FROM CUSTOMERS
),
ACTIVITIES AS (
SELECT CO.*,DATE_TRUNC('MONTH',O.ORDER_DATE) AS ORDER_MON,
EXTRACT(YEAR FROM AGE(DATE_TRUNC('MONTH',O.ORDER_DATE),CO.COHORT_MONTH))*12 + EXTRACT(MONTH FROM AGE(DATE_TRUNC('MONTH',O.ORDER_DATE),CO.COHORT_MONTH)) AS MONTHS_SINCE_SIGNUP
FROM COHORT CO
JOIN ORDERS O ON O.CUSTOMER_ID=CO.CUSTOMER_ID
WHERE O.STATUS='Delivered'
) 
SELECT 
	TO_CHAR(C.COHORT_MONTH,'MON-YYYY') AS MONTH,
	COUNT(DISTINCT C.CUSTOMER_ID) AS COHORT_SIZE,
	COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=0 THEN C.CUSTOMER_ID END ) AS MONTH_0,
	COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=1 THEN C.CUSTOMER_ID END ) AS MONTH_1,
	COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=2 THEN C.CUSTOMER_ID END ) AS MONTH_2,
	COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=3 THEN C.CUSTOMER_ID END ) AS MONTH_3,
	COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=4 THEN C.CUSTOMER_ID END ) AS MONTH_4,
	COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=5 THEN C.CUSTOMER_ID END ) AS MONTH_5,
	COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=6 THEN C.CUSTOMER_ID END ) AS MONTH_6,
	COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=7 THEN C.CUSTOMER_ID END ) AS MONTH_7,
	COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=8 THEN C.CUSTOMER_ID END ) AS MONTH_8,
	COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=9 THEN C.CUSTOMER_ID END ) AS MONTH_9,
	COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=10 THEN C.CUSTOMER_ID END ) AS MONTH_10,
	ROUND(COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=1 THEN C.CUSTOMER_ID END )::numeric/NULLIF(COUNT(DISTINCT C.CUSTOMER_ID),0)*100,2) AS retention_m1_pct,
	ROUND(COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=2 THEN C.CUSTOMER_ID END )::numeric/NULLIF(COUNT(DISTINCT C.CUSTOMER_ID),0)*100,2) AS retention_m2_pct,
	ROUND(COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=3 THEN C.CUSTOMER_ID END )::numeric/NULLIF(COUNT(DISTINCT C.CUSTOMER_ID),0)*100,2) AS retention_m3_pct,
	ROUND(COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=4 THEN C.CUSTOMER_ID END )::numeric/NULLIF(COUNT(DISTINCT C.CUSTOMER_ID),0)*100,2) AS retention_m4_pct,
	ROUND(COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=5 THEN C.CUSTOMER_ID END )::numeric/NULLIF(COUNT(DISTINCT C.CUSTOMER_ID),0)*100,2) AS retention_m5_pct,
	ROUND(COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=6 THEN C.CUSTOMER_ID END )::numeric/NULLIF(COUNT(DISTINCT C.CUSTOMER_ID),0)*100,2) AS retention_m6_pct,
	ROUND(COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=7 THEN C.CUSTOMER_ID END )::numeric/NULLIF(COUNT(DISTINCT C.CUSTOMER_ID),0)*100,2) AS retention_m7_pct,
	ROUND(COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=8 THEN C.CUSTOMER_ID END )::numeric/NULLIF(COUNT(DISTINCT C.CUSTOMER_ID),0)*100,2) AS retention_m8_pct,
	ROUND(COUNT(DISTINCT CASE WHEN MONTHS_SINCE_SIGNUP=9 THEN C.CUSTOMER_ID END )::numeric/NULLIF(COUNT(DISTINCT C.CUSTOMER_ID),0)*100,2) AS retention_m9_pct
FROM ACTIVITIES A
JOIN COHORT C ON C.CUSTOMER_ID=A.CUSTOMER_ID
GROUP BY C.COHORT_MONTH

/*
"Build me the ULTIMATE customer intelligence report. Every metric, every customer."

For ALL customers:
1. name, city, tenure_months
2. recency_days, frequency, monetary (RFM raw)
3. r_score, f_score, m_score (NTILE)
4. rfm_segment (Champion/Loyal/At Risk/Lost/etc.)
5. monthly_value (revenue/months)
6. annual_clv (monthly × 12)
7. clv_rank (DENSE_RANK by CLV)
8. spending_quartile (NTILE(4) by monetary)
9. revenue_share_pct (vs company total)
10. category_count (correlated subquery)
11. churn_risk (High/Medium/Low based on recency)*/

WITH ORDER_DATA AS (
SELECT 
	C.CUSTOMER_ID,
	C.NAME,
	C.CITY,
	C.SIGNUP_DATE,
	(EXTRACT(YEAR FROM AGE(DATE_TRUNC('MONTH',C.SIGNUP_DATE))))*12 + 	
	EXTRACT(MONTH FROM AGE(DATE_TRUNC('MONTH',C.SIGNUP_DATE))) AS tenure_months,
	CURRENT_DATE - MAX(O.ORDER_DATE) AS recency_days,
	COUNT(DISTINCT O.ORDER_ID)	AS frequency,
	SUM(OI.QUANTITY*P.PRICE)	AS monetary
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID AND O.STATUS='Delivered'
LEFT JOIN ORDER_ITEMS OI ON OI.ORDER_ID=O.ORDER_ID
LEFT JOIN PRODUCTS P ON P.PRODUCT_ID=OI.PRODUCT_ID
GROUP BY C.CUSTOMER_ID,2,4
),
FRM_SCORE AS (
SELECT D.CUSTOMER_ID,D.NAME, D.CITY, D.tenure_months, recency_days, frequency, monetary,
	NTILE(4) OVER(ORDER BY recency_days) AS R_SCORE,
	NTILE(4) OVER(ORDER BY frequency DESC) AS F_SCORE,
	NTILE(4) OVER(ORDER BY MONETARY DESC) AS M_SCORE
FROM ORDER_DATA D
)
SELECT *, 
	CASE 
			WHEN R_SCORE=1 AND F_SCORE=1 AND M_SCORE=1 THEN 'CHAMPION'
			WHEN R_SCORE=1 AND F_SCORE=1 THEN 'LOYAL CUSTOMERS'
			WHEN R_SCORE=1 AND M_SCORE=1 THEN 'BIG SPENDERS'
			WHEN R_SCORE=3 AND F_SCORE=1 THEN 'AT RISK'
			WHEN R_SCORE=4 AND F_SCORE=4 AND M_SCORE=4 THEN 'LOST'
			WHEN F_SCORE=1 AND M_SCORE=1 THEN 'LOYAL BIG SPENDERS'
			ELSE 'NEED ATTENTION'
			END AS rfm_segment,
	ROUND(monetary/frequency,2) AS MONTHLY_VALUE,
	ROUND(MONETARY::NUMERIC/NULLIF(tenure_months,0)*100,2) AS ANNUAL_CLV,
	DENSE_RANK() OVER(ORDER BY ROUND(MONETARY::NUMERIC/NULLIF(tenure_months,0)*100,2) DESC)	AS clv_rank,
	NTILE(4) OVER(ORDER BY MONETARY DESC NULLS LAST ) AS spending_quartile,
	COALESCE(ROUND(MONETARY::NUMERIC/NULLIF((SELECT SUM(FRM2.MONETARY) FROM FRM_SCORE FRM2),0)*100,2),0) AS revenue_share_pct,
	(SELECT distinct count(P2.CATEGORY) FROM PRODUCTS P2
		JOIN ORDER_ITEMS OI2 ON OI2.PRODUCT_ID=P2.PRODUCT_ID
		JOIN ORDERS O2 ON O2.ORDER_ID=OI2.ORDER_ID
		WHERE O2.CUSTOMER_ID=FRM_SCORE.customer_id AND O2.STATUS='Delivered') as CATEGORY_COUNT,
	 CASE
	 	WHEN recency_days IS NULL THEN 'LOST'
        WHEN recency_days=9999 THEN 'High'
        WHEN recency_days>90 THEN 'High'
        WHEN recency_days>60 THEN 'Medium'
        ELSE 'Low' END AS churn_risk	
FROM FRM_SCORE
ORDER BY MONETARY DESC NULLS LAST








